### PR TITLE
Update to logstash 1.5.x

### PR DESCRIPTION
**Pull request by MWilkinson**
Hi Bitsofinfo,
   first, thanks for spending the time putting together this logstash config - it's great !

I'm looking at deploying it to site, and noticed a couple of niggles, here's a PR which fixes the following
  - Remove the deprecated warning from the file { charset => } and multiline { type => }
  - Extract all the tags from the Message line (not just the first)
  - Removed the nil severities entry (from msg's that don't have a severity item)

I've also expanded the ruby code to make it easier for people to understand what the ruby code is doing (ie me) and added an example to split all the request cookies into a first class field

It now runs cleanly on a logstash-1.5.4 instance for me

regards

### CODE REVIEW

**Comment by bitsofinfo** [comment]
Sorry missed this, does this run on 1.4.x? Wondering if I should do a 1.4.x "release", before pushing this into mainline

**Comment by bitsofinfo** [comment]
Also if this changes the format of the output JSON, the README should be updated. 

I created a release 1.0 for the existing mainline. I encountered another issue with request/response headers. In 1.5.x they are not properly being parsed and separated out. Did you encounter this too?

**Comment by MWilkinson** [comment]
Hmm. Can't remember off the top of my head.
But i'll certainly take another look through my log files tomorrow.

Regards
Mark

**Comment by bitsofinfo** [comment]
Also take a look at my changes @ https://github.com/bitsofinfo/logstash-modsecurity/commit/732b29a1198ed9c156d49382ba6937cf068c138c

You will want to re-merge your changes w/ the latest and adjust the PR

**Comment by bitsofinfo** [comment]
see #18

**Comment by MWilkinson** [comment]
Hi BitsOfInfo,
  I've updated my fork/pull request in line with the current base.

Sorry for the delay

**Pull request merged**
